<a href="https://colab.research.google.com/github/wambui-nduta/nduts/blob/main/Artificial_Neural_Network_Checkpoint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelBinarizer

In [15]:

# Load data
iris = load_iris()
X = iris.data
y = iris.target


In [3]:
# Normalize features
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [16]:
# One-hot encode labels
encoder = LabelBinarizer()
y = encoder.fit_transform(y)

In [17]:

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(64, input_shape=(X_train.shape[1],), activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(y_train.shape[1], activation='softmax'))  # softmax for multi-class


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [19]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])


In [20]:
history = model.fit(X_train, y_train,
                    validation_split=0.2,  # optional for MNIST
                    epochs=20,
                    batch_size=32,
                    verbose=1)


Epoch 1/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 132ms/step - accuracy: 0.0508 - loss: 1.2810 - val_accuracy: 0.0417 - val_loss: 1.2013
Epoch 2/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.1315 - loss: 1.1899 - val_accuracy: 0.0833 - val_loss: 1.1159
Epoch 3/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.2057 - loss: 1.1029 - val_accuracy: 0.4583 - val_loss: 1.0721
Epoch 4/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.4831 - loss: 1.0558 - val_accuracy: 0.2917 - val_loss: 1.0372
Epoch 5/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.3880 - loss: 1.0161 - val_accuracy: 0.2917 - val_loss: 1.0043
Epoch 6/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.4102 - loss: 0.9831 - val_accuracy: 0.5000 - val_loss: 0.9657
Epoch 7/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6302 - loss: 0.9579 - val_accuracy: 0.9167 - val_loss: 0.9207
Epoch 8/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9375 - loss: 0.9180 - val_accuracy: 0.9583 - val_loss: 0.8905

In [21]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import numpy as np

# Predict
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

# Confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_true, y_pred_classes))

# Classification report
print("\nClassification Report:")
print(classification_report(y_true, y_pred_classes))

# Accuracy percentage
accuracy = accuracy_score(y_true, y_pred_classes)
print(f"\nOverall Accuracy: {accuracy * 100:.2f}%")





1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step
Confusion Matrix:
[[10  0  0]
 [ 0  8  1]
 [ 0  1 10]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.89      0.89      0.89         9
           2       0.91      0.91      0.91        11

    accuracy                           0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30


Overall Accuracy: 93.33%


## **Option 2: MNIST Dataset**

In [10]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

# Load data
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# Reshape and normalize
X_train = X_train.reshape(-1, 784).astype("float32") / 255.0
X_test = X_test.reshape(-1, 784).astype("float32") / 255.0

# One-hot encode labels
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)


11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [22]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()


In [23]:
# 3. Preprocess the data

# Flatten 28x28 images into 784-element vectors
X_train = X_train.reshape(-1, 784).astype("float32") / 255.0
X_test = X_test.reshape(-1, 784).astype("float32") / 255.0

# One-hot encode the labels
y_train_encoded = to_categorical(y_train)
y_test_encoded = to_categorical(y_test)


In [24]:
# 4. Build the model
model = Sequential()
model.add(Dense(128, input_shape=(784,), activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(10, activation='softmax'))  # 10 classes for digits 0–9


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [26]:
# 5. Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])


In [27]:
# 6. Train the model
model.fit(X_train, y_train_encoded,
          validation_split=0.1,
          epochs=10,
          batch_size=32,
          verbose=1)


Epoch 1/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8634 - loss: 0.4603 - val_accuracy: 0.9663 - val_loss: 0.1188
Epoch 2/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - accuracy: 0.9637 - loss: 0.1180 - val_accuracy: 0.9700 - val_loss: 0.1078
Epoch 3/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9771 - loss: 0.0741 - val_accuracy: 0.9738 - val_loss: 0.0894
Epoch 4/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.9828 - loss: 0.0556 - val_accuracy: 0.9732 - val_loss: 0.0947
Epoch 5/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9863 - loss: 0.0420 - val_accuracy: 0.9753 - val_loss: 0.0862
Epoch 6/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.9889 - loss: 0.0356 - val_accuracy: 0.9735 - val_loss: 0.1079
Epoch 7/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9908 - loss: 0.0278 - val_accuracy: 0.9783 - val_loss: 0.0935
Epoch 8/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - accuracy: 0.9915 - loss: 0.0251 

In [28]:
# 7. Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test_encoded, verbose=0)
print(f"\nTest Accuracy: {accuracy * 100:.2f}%")



Test Accuracy: 97.77%


In [29]:
# 8. Detailed evaluation: Confusion matrix + classification report
y_pred_probs = model.predict(X_test)
y_pred_classes = np.argmax(y_pred_probs, axis=1)
y_true = y_test  # not one-hot encoded

print("\nConfusion Matrix:")
cm = confusion_matrix(y_true, y_pred_classes)
print(cm)

print("\nClassification Report:")
print(classification_report(y_true, y_pred_classes))

# Optional: Plot confusion matrix
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=range(10), yticklabels=range(10))
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()


313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

Confusion Matrix:
[[ 967    0    0    2    0    5    1    2    2    1]
 [   0 1113    2    5    0    0    2    1   12    0]
 [   1    0 1005    7    0    0    1    8    9    1]
 [   0    0    2  990    0    4    0    5    4    5]
 [   0    0    0    1  965    0    5    2    0    9]
 [   1    0    0   18    1  862    1    0    4    5]
 [   4    2    2    1    8    6  929    0    6    0]
 [   1    0    6    1    2    1    0 1009    2    6]
 [   2    0    3    5    2    4    0    2  952    4]
 [   2    2    0    1    5    5    1    7    1  985]]

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       980
           1       1.00      0.98      0.99      1135
           2       0.99      0.97      0.98      1032
           3       0.96      0.98      0.97      1010
           4       0.98      0.98      0.98       982
           5       0.97      0.97      0.97       892
      

NameError: name 'plt' is not defined