<a href="https://colab.research.google.com/github/wambui-nduta/nduts/blob/main/NumPY_checkpoint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
grades_arr=  [85, 90, 88, 92, 95, 80, 75, 98, 89, 83]

mean_grades = np.mean(grades_arr)

print (mean_grades)




87.5


In [2]:
median_grades = np.median(grades_arr)

print (median_grades)

88.5


In [3]:
std_grades = np.std(grades_arr)

print (std_grades)

6.591661399070799


In [4]:
grades_arr =  [85, 90, 88, 92, 95, 80, 75, 98, 89, 83]
min_grades = np.min(grades_arr)
max_grades = np.max(grades_arr)

print (min_grades)
print (max_grades)

75
98


In [5]:
grades_arr =np.sort(grades_arr)
print (grades_arr)

[75 80 83 85 88 89 90 92 95 98]


In [16]:
grades_arr= [85, 90, 88, 92, 95, 80, 75, 98, 89, 83]
max_index = np.argmax(grades_arr)
print (max_index)

7


In [24]:
import numpy as np

grades_arr = np.array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])  # Use parentheses

indices = np.where(grades_arr > 90)
print(indices)


(array([3, 4, 7]),)


In [25]:
import numpy as np

grades_arr = np.array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

percentage = (np.sum(grades_arr > 90) / grades_arr.size) * 100

print(f"Percentage of students who scored above 90: {percentage:.2f}%")


Percentage of students who scored above 90: 30.00%


In [26]:
import numpy as np

grades_arr = np.array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

percentage_below_75 = (np.sum(grades_arr < 75) / grades_arr.size) * 100

print(f"Percentage of students who scored below 75: {percentage_below_75:.2f}%")


Percentage of students who scored below 75: 0.00%


In [27]:
import numpy as np

grades_arr = np.array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

high_performers = grades_arr[grades_arr > 90]

print(high_performers)


[92 95 98]


In [28]:
import numpy as np

grades_arr = np.array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

passing_grades = grades_arr[grades_arr > 75]

print(passing_grades)


[85 90 88 92 95 80 98 89 83]


#Create a numpy array called "grades" that contains the following grades: [85, 90, 88, 92, 95, 80, 75, 98, 89, 83]

#Use numpy functions to calculate the mean, median, and standard deviation of the grades.
#Use numpy function to find the maximum and minimum of the grades.
#Use numpy function to sort the grades in ascending order.
#Use numpy function to find the index of the highest grade in the array.
#Use numpy function to count the number of students who scored above 90.
#Use numpy function to calculate the percentage of students who scored above 90.
#Use numpy function to calculate the percentage of students who scored below 75.
#Use numpy function to extract all the grades above 90 and put them in a new array called "high_performers".
#$Print the result of all the above steps.
