<a href="https://colab.research.google.com/github/wambui-nduta/nduts/blob/main/numpy_prac_self.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
array_rng = np.arange(start=0, stop=30, step=2.5)
print(array_rng)


[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5 25.  27.5]


In [5]:
array_full = np.full(shape=(2, 3), fill_value=2)
array_full_text = np.full(shape=(2, 3), fill_value='Three-Six-Five')

print(array_full)
print(array_full_text)

[[2 2 2]
 [2 2 2]]
[['Three-Six-Five' 'Three-Six-Five' 'Three-Six-Five']
 ['Three-Six-Five' 'Three-Six-Five' 'Three-Six-Five']]


In [10]:
array_0s = np.zeros(shape=(10))
print(array_0s)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
array_0s = np.zeros(shape=(2, 3))
print(array_0s)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
matrix_A = np.array([[1, 0, 9, 2, 2], [3, 23, 4, 5, 1], [0, 2, 3, 4, 1]])
array_empty_like = np.empty_like(matrix_A)

print(array_empty_like)

[[           34261578                   0        206158430253
         193273528371        214748364849]
 [       210453397588        249108103223        223338299441
         210453397562        197568495672]
 [       231928234036        236223201328        210453397552
  8286623670843998298                 128]]
